<?php
/**
 * @file
 * Custom code for the PackWeb module.
 */

/**
 * Implements hook_block_info().
 */
function pw_module_block_info() {
  return array(
    'packweb' => array(
      'info' => t('PackWeb'),
      'description' => t('"Site by PackWeb" link.'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function pw_module_block_view($delta = '', $settings = array(), $contexts = array()) {
  switch ($delta) {
    case 'packweb':
      $block['subject'] = NULL;
      $block['content'] = t('Site by <a href="https://www.packweb.com.au/">PackWeb</a>.');
    break;
    default:
      $block = array();
  }

  return $block;
}

